project:
  type: book
  output-dir: html_outputs
  
published-title: "Last updated"
  
# profile:
#   default: full
#   group: 
#     - [full, small]
lightbox: true # Lightbox images allow a reader to click to see a larger version of the image (including any caption)

babelquarto:
  languagecodes:
  - name: vn
    text: "Tiếng Việt"
  - name: fr
    text: "Français"
  - name: es
    text: "Español"
  - name: jp
    text: "日本"
  - name: tr
    text: "Türkçe"
  - name: pt
    text: "Português"
  - name: ru
    text: "Русский"
  - name: de
    text: "Deutsch"
  - name: en
    text: "English"

  mainlanguage: 'en'
  languages: ['fr', 'es', 'vn', 'jp', 'pt', 'tr', 'ru']  #'de'  fr

title-vn: "Cẩm nang dịch tễ học với R"
title-fr: "Le Epi R Handbook"
title-es: "EpiRhandbook en español"
title-jp: "疫学のための R ハンドブック"
title-tr: "Epidemiyologun R Rehberi"
title-pt: "Manual de R para Epidemiologistas"
title-ru: "Справочник эпидемиолога R"
title-de: "EpiRhandbook auf Deutsch"

lang: en

format:
  html: 
    include-in-header:
      - banner.html
    theme:
      light: cosmo
      dark: [darkly, theme-dark.scss]

book:
  title: "The Epidemiologist R Handbook"
  search:
    type: textbox
  repo-url: https://github.com/appliedepi/epiRhandbook_eng
  # site-url: https://epirhandbook.com
  sharing: ["twitter", "facebook", "linkedin"]
  sidebar:
    logo: "images/Applied_Epi_logo.png"
    tools:
      - icon: twitter
        href: "https://twitter.com/appliedepi"
      - icon: linkedin
        href: "https://www.linkedin.com/company/appliedepi/"
      # - icon: github
      #   menu:
      #     - text: Source Code
      #       url: "https://github.com/appliedepi/epihandbook_eng"
      #     - text: Report a Bug
      #       url: "https://github.com/appliedepi/epihandbook_eng/issues/new"

  date: today
  date-format: "MMM D, YYYY"
  favicon: "images/Applied_Epi_logo.png"
  cookie-consent:
    type: implied
    style: simple
    palette: dark
  google-analytics:
    tracking-id: "G-QXDW878QLX"
    storage: cookies
    anonymize-ip: true

  chapters:
  # INTRO & CONTRIBUTORS
  - index.qmd                              # objectives, how to read, authors, acknowledgements

  # ABOUT BOOK
  - part: "About this book"
    part-vn: "Về cuốn sách này" 
    part-fr: "À propos de ce livre"
    part-es: "Acerca de este libro"
    part-jp: "本書について"
    part-tr: "Bu kitap hakkında"
    part-pt: "Sobre este livro"
    part-ru: "Об этой книге"
    part-de: "Über dieses Buch"
    chapters:
    - chapters/editorial_style.qmd          # editorial style
    - chapters/data_used.qmd                # data used

  # BASICS
  - part: "Basics"
    part-vn: "Nhập môn về R"
    part-fr: "Les bases de R"
    part-es: "Aspectos básicos"
    part-jp: "基本編"
    part-tr: "Temel Bilgiler"
    part-pt: "Básico"
    part-ru: "Основы"
    part-de: "Grundlagen"
    chapters:
    - chapters/basics.qmd
    - chapters/transition_to_r.qmd
    - chapters/packages_suggested.qmd
    - chapters/r_projects.qmd
    - chapters/importing.qmd

  # DATA MANAGEMENT
  - part: "Data Management"
    part-vn: "Quản lý dữ liệu"
    part-fr: "Gestion des données"
    part-es: "Gestión de datos"
    part-jp: "データマネジメント"
    part-tr: "Veri Yönetimi"
    part-pt: "Gerenciamento de Dados"
    part-ru: "Управление данными"
    part-de: "Datenmanagement"
    chapters:
    - chapters/cleaning.qmd
    - chapters/dates.qmd
    - chapters/characters_strings.qmd
    - chapters/factors.qmd
    - chapters/pivoting.qmd
    - chapters/grouping.qmd
    - chapters/joining_matching.qmd
    - chapters/deduplication.qmd
    - chapters/iteration.qmd

  # ANALYSIS
  - part: "Analysis"
    part-vn: "Phân tích dữ liệu"
    part-fr: "Analyse"
    part-es: "Análisis"
    part-jp: "データ分析"
    part-tr: "Analiz"
    part-pt: "Análise dos Dados"
    part-ru: "Анализ"
    part-de: "Analyse"
    chapters:
    - chapters/tables_descriptive.qmd
    - chapters/stat_tests.qmd
    - chapters/regression.qmd
    - chapters/missing_data.qmd
    - chapters/standardization.qmd
    - chapters/moving_average.qmd
    - chapters/time_series.qmd #done
    #- chapters/epidemic_models.qmd EXCLUDED-epinow2-defunct-accessors
    - chapters/contact_tracing.qmd #done
    - chapters/survey_analysis.qmd #done
    - chapters/survival_analysis.qmd #done
    #- chapters/gis.qmd EXCLUDED-osm-external-dep

  # DATA VIZ
  - part: "Data Visualization"
    part-vn: "Trực quan hóa dữ liệu"
    part-fr: "Visualisation des données"
    part-es: "Visualización de datos"
    part-jp: "データの可視化"
    part-tr: "Veri Görselleştirme"
    part-pt: "Visualização de Dados"
    part-ru: "Визуализация данных"
    part-de: "Datenvisualisierung"
    chapters:
    - chapters/tables_presentation.qmd  #done
    - chapters/ggplot_basics.qmd #done
    #chapters/plot_continuous.qmd,
    #chapters/plot_discrete.qmd,
    - chapters/ggplot_tips.qmd #done
    - chapters/epicurves.qmd #done
    - chapters/age_pyramid.qmd #done
    - chapters/heatmaps.qmd   #done
    - chapters/diagrams.qmd  #done
    - chapters/combination_analysis.qmd #done
    - chapters/transmission_chains.qmd #done
    - chapters/phylogenetic_trees.qmd #done
    - chapters/interactive_plots.qmd #done

  # REPORTS AND DASHBOARDS
  - part: "Reports and dashboards"
    part-vn: "Báo cáo và dashboards"
    part-fr: "Rapports et tableaux de bord"
    part-es: "Informes y Dashboards"
    part-jp: "レポートとダッシュボード"
    part-tr: "Raporlar ve gösterge panoları"
    part-pt: "Relatórios e dashboards"
    part-ru: "Отчеты и информационные панели"
    part-de: "Berichte und Dashboards"
    chapters:
    - chapters/rmarkdown.qmd #done
    - chapters/reportfactory.qmd #done
    - chapters/flexdashboard.qmd #done
    - chapters/shiny_basics.qmd #done

  # MISCELLANEOUS
  - part: "Miscellaneous"
    part-vn: "Các chủ điểm khác"
    part-fr: "Autres sujets"
    part-es: "Miscelánea"
    part-jp: "その他"
    part-tr: "Çeşitli"
    part-pt: "Miscelânea"
    part-ru: "Разное"
    part-de: "Verschiedenes"
    chapters:
    - chapters/writing_functions.qmd #done
    - chapters/directories.qmd #done
    - chapters/collaboration.qmd #done
    - chapters/errors.qmd #done
    - chapters/help.qmd #done
    #chapters/relational_databases.qmd,
    - chapters/network_drives.qmd #done
    - chapters/data_table.qmd #done
    # chapters/rstudio_advanced.qmd

